services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./data:/app/data
      - ./server:/app/server
      - ./client:/app/client
      - ./package.json:/app/package.json
      - ./knexfile.js:/app/knexfile.js
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_PATH=/app/node_modules
    command: npm run dev:concurrently
    restart: unless-stopped