services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3001:3000" # Use a different port to avoid conflict with dev server
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    # Run tests and then exit
    command: npm run test:server
volumes:
  node_modules: {}